### ISSUE TITLE
Selecting the means of transport

### ISSUE THREAD

**Issue by sebkur** [juliuste/direkt.bahn.guru#2]
How about an option to select the means of transport to take into account. I'd like to see this in order to show reachability with regional trains only. Would it be hard to implement that?

**Comment by MartinEnders** [comment]
This feature would be super cool in Germany for the 9€ ticket which is available from June to August.
The 9€ ticket allows to travel across Germany but not in ICE, IC, and EC trains.

PS: Your website is really great 👍

**Comment by juliuste** [comment]
Thanks for the suggestion! The hurdle for implementing this is similar to that for #4 (see my comment there): Adding such a filter mechanism to the API is really straight-forward, but exposing that filter to the users in the frontend is a bit of work. I will look into that in the future, but if someone else wants to implement the UI before, I'd also be grateful 🙂

**Comment by juliuste** [comment]
Since this issue was raised multiple times (probably because of the [9 euro ticket](https://www.bahn.de/angebot/regio/9-euro-ticket) over the last few days, I changed my mind and spent a few hours to quickly cobble something together in really basic way. There should now be a filter icon below the search bar, allowing users to switch between all transit and local-only. Note that (because of technical restrictions, once again) some trains might be wrongly categorized as local. I already filtered some of these out in the backend (e.g. Flixtrain), but since these exceptions need to be hard-coded on a case-by-case basis, I probably missed some.

I'll close this issue for now, but please comment/re-open if something is broken, or if I misunderstood the original feature request.

**Comment by MartinEnders** [comment]
Thank you @juliuste

**Comment by sebkur** [comment]
Thanks for implementing this!
